apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
  type: nodePort
  ports:
  - protocol: TCP
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: nginx

