#Secret password is 123
apiVersion: v1
data:
  password: MTIz
kind: Secret
type: Opaque
metadata:
  creationTimestamp: null
  name: dbsecret
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: database
  name: database
spec:
  containers:
  - image: mysql
    name: database
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dbsecret
          key: password
    volumeMounts:
    - name: dbsecret
      mountPath: "/etc/dbsecret"
      readOnly: true
  volumes:
  - name: dbsecret
    secret:
      secretName: dbsecret