apiVersion: v1
data:
  password: "12345"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: webapp
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: database
  name: database
spec:
  containers:
  - image: mysql
    name: database
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        configMapKeyRef:
          name: webconfigmap
          key: password
    volumeMounts:
    - name: webconfigmap
      mountPath: "/etc/webconfigmap"
      readOnly: true
  volumes:
  - name: webconfigmap
    configMap:
    name: webconfigmap