apiVersion: v1
kind: Pod
metadata:
  labels:
  name: www-liveness-probe
spec:
  containers:
  - name: www-liveness-probe
    image: k8s.gcr.io/nginx
    livenessProbe:
      exec:
        command:
        - touch
        - /var/www/html/hello-world.txt
      initialDelaySeconds: 30
      periodSeconds: 5
---
apiVersion: v1
kind: Pod
metadata:
  labels:
  name: www-liveness-probe
spec:
  containers:
  - name: www-liveness-probe
    image: k8s.gcr.io/nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 5