apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: initpod
  name: initpod
spec:
  containers:
  - image: nginx
    name: www
  initContainers:
  - image: busybox
    name: initpod
    command: ["sleep"]
    args: ["5"]